#1065 Add matchers for Regex
kotest/kotest pull request #1074
Opened 2019-11-06 17:47 UTC by ashishkujoy

2019-11-07 08:46 UTC, ashishkujoy commented
Hi, @Kerooker  looking for feedback on this.

2019-11-07 13:05 UTC, ashishkujoy commented
Will add documentation for this as a separate PR

2019-11-11 14:41 UTC, ashishkujoy commented
@Kerooker Any update on this PR.

2019-11-11 15:13 UTC, sksamuel requested changes
This is a great PR. Just a couple of small points to address.

2019-11-11 15:13 UTC, sksamuel commented on kotest-assertions/src/commonMain/kotlin/io/kotest/matchers/regex/RegexMatchers.kt
> +infix fun Regex.shouldHaveRegexOptions(regexOptions: Set<RegexOption>) = this should haveOptions(regexOptions)
Since this is not "exact" lets rename this to `shouldIncludeRegexOptions`
same for all the non-exact ones.

2019-11-11 15:13 UTC, sksamuel commented on kotest-assertions/src/commonMain/kotlin/io/kotest/matchers/regex/RegexMatchers.kt
> +infix fun Regex.shouldBeRegex(anotherRegex: Regex) = this should beRegex(anotherRegex)
Can we place the infix versions one line above the non infix so it's easy to see which have infix and which dont ?

2019-11-11 15:13 UTC, sksamuel commented on kotest-assertions/src/commonMain/kotlin/io/kotest/matchers/regex/RegexMatchers.kt
> +infix fun Regex.shouldHavePattern(regexPattern: String) = this should havePatter(regexPattern)
havePatter is a typo.

2019-11-11 15:13 UTC, sksamuel commented on kotest-assertions/src/commonMain/kotlin/io/kotest/matchers/regex/RegexMatchers.kt
> +fun havePatter(pattern: String) = haveSamePatternMatcher(pattern)
havePatter

2019-11-11 17:53 UTC, sksamuel approved these changes

2019-11-11 17:53 UTC, merged

2019-11-11 17:53 UTC, sksamuel commented
Awesome. Merged.