Add Spec EnabledIf
kotest/kotest pull request #1687
Opened 2020-09-04 05:01 UTC by LeoColman

This commit adds the @EnabledIf annotation for specs. The way that Kotlin handles annotations isn't very fexible, and thus
using this annotation is verbose and repetitive. We must reference a class, as we can't reference just a single method as we do for
Test EnabledIf.

This currently only works on JVM, as does @Ignored.

Closes #1683

2020-09-04 05:02 UTC, LeoColman commented
This is still missing some docs. 
I'll get to it if the syntax is agreed upon.

2020-09-04 05:24 UTC, sksamuel commented on kotest-framework/kotest-framework-api/src/commonMain/kotlin/io/kotest/core/annotation/specAnnotations.kt
> +annotation class EnabledIf<T : SpecEnabledIf>(val enabledIf: KClass<T>)
I was thinking something along the lines of

`annotation class EnabledIf(val test: (KClass<*> -> Boolean)`

2020-09-04 05:38 UTC, LeoColman commented
That doesn't compile

On Fri., Sep. 4, 2020, 02:25 Sam Sam, <notifications@github.com> wrote:

> *@sksamuel* commented on this pull request.
> ------------------------------
>
> In
> kotest-framework/kotest-framework-api/src/commonMain/kotlin/io/kotest/core/annotation/specAnnotations.kt
> <https://github.com/kotest/kotest/pull/1687#discussion_r483393855>:
>
> > @@ -16,3 +19,17 @@ annotation class Tags(vararg val values: String)
>  @Target(AnnotationTarget.CLASS)
>  @Retention(AnnotationRetention.RUNTIME)
>  annotation class Ignored
> +
> +/**
> + * Attach to [io.kotest.core.spec.Spec], and the logic inside [enabledIf] will be executed
> + * to define if a test will be instantiated or executed.
> + *
> + * [SpecEnabaledIf] must contain a no-arg constructor as it will be used via reflection.
> + */
> +@Target(AnnotationTarget.CLASS)
> +@Retention(AnnotationRetention.RUNTIME)
> +annotation class EnabledIf<T : SpecEnabledIf>(val enabledIf: KClass<T>)
>
> I was thinking something along the lines of
>
> annotation class EnabledIf(val test: (KClass<*> -> Boolean)
>
> —
> You are receiving this because you were assigned.
> Reply to this email directly, view it on GitHub
> <https://github.com/kotest/kotest/pull/1687#pullrequestreview-482366436>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAMBCI3PFROQD3GAYEJCNOTSEB23PANCNFSM4QXE5EOQ>
> .
>

2020-09-04 05:39 UTC, LeoColman commented
Unless I looked at it wrong. Annotations must be constants at compile time

On Fri., Sep. 4, 2020, 02:36 Leonardo Colman Lopes, <
leonardo.dev@colman.com.br> wrote:

> That doesn't compile
>
> On Fri., Sep. 4, 2020, 02:25 Sam Sam, <notifications@github.com> wrote:
>
>> *@sksamuel* commented on this pull request.
>> ------------------------------
>>
>> In
>> kotest-framework/kotest-framework-api/src/commonMain/kotlin/io/kotest/core/annotation/specAnnotations.kt
>> <https://github.com/kotest/kotest/pull/1687#discussion_r483393855>:
>>
>> > @@ -16,3 +19,17 @@ annotation class Tags(vararg val values: String)
>>  @Target(AnnotationTarget.CLASS)
>>  @Retention(AnnotationRetention.RUNTIME)
>>  annotation class Ignored
>> +
>> +/**
>> + * Attach to [io.kotest.core.spec.Spec], and the logic inside [enabledIf] will be executed
>> + * to define if a test will be instantiated or executed.
>> + *
>> + * [SpecEnabaledIf] must contain a no-arg constructor as it will be used via reflection.
>> + */
>> +@Target(AnnotationTarget.CLASS)
>> +@Retention(AnnotationRetention.RUNTIME)
>> +annotation class EnabledIf<T : SpecEnabledIf>(val enabledIf: KClass<T>)
>>
>> I was thinking something along the lines of
>>
>> annotation class EnabledIf(val test: (KClass<*> -> Boolean)
>>
>> —
>> You are receiving this because you were assigned.
>> Reply to this email directly, view it on GitHub
>> <https://github.com/kotest/kotest/pull/1687#pullrequestreview-482366436>,
>> or unsubscribe
>> <https://github.com/notifications/unsubscribe-auth/AAMBCI3PFROQD3GAYEJCNOTSEB23PANCNFSM4QXE5EOQ>
>> .
>>
>

2020-09-04 05:49 UTC, sksamuel commented
What about:

annotation class EnabledIf(val test: KClass<EnabledCondition>)

abstract class EnabledCondition {
   abstract fun test(kClass: KClass<out Spec>): Boolean
}


On Fri, 4 Sep 2020 at 00:39, Leonardo Colman <notifications@github.com>
wrote:

> Unless I looked at it wrong. Annotations must be constants at compile time
>
> On Fri., Sep. 4, 2020, 02:36 Leonardo Colman Lopes, <
> leonardo.dev@colman.com.br> wrote:
>
> > That doesn't compile
> >
> > On Fri., Sep. 4, 2020, 02:25 Sam Sam, <notifications@github.com> wrote:
> >
> >> *@sksamuel* commented on this pull request.
> >> ------------------------------
> >>
> >> In
> >>
> kotest-framework/kotest-framework-api/src/commonMain/kotlin/io/kotest/core/annotation/specAnnotations.kt
> >> <https://github.com/kotest/kotest/pull/1687#discussion_r483393855>:
> >>
> >> > @@ -16,3 +19,17 @@ annotation class Tags(vararg val values: String)
> >> @Target(AnnotationTarget.CLASS)
> >> @Retention(AnnotationRetention.RUNTIME)
> >> annotation class Ignored
> >> +
> >> +/**
> >> + * Attach to [io.kotest.core.spec.Spec], and the logic inside
> [enabledIf] will be executed
> >> + * to define if a test will be instantiated or executed.
> >> + *
> >> + * [SpecEnabaledIf] must contain a no-arg constructor as it will be
> used via reflection.
> >> + */
> >> +@Target(AnnotationTarget.CLASS)
> >> +@Retention(AnnotationRetention.RUNTIME)
> >> +annotation class EnabledIf<T : SpecEnabledIf>(val enabledIf: KClass<T>)
> >>
> >> I was thinking something along the lines of
> >>
> >> annotation class EnabledIf(val test: (KClass<*> -> Boolean)
> >>
> >> —
> >> You are receiving this because you were assigned.
> >> Reply to this email directly, view it on GitHub
> >> <https://github.com/kotest/kotest/pull/1687#pullrequestreview-482366436
> >,
> >> or unsubscribe
> >> <
> https://github.com/notifications/unsubscribe-auth/AAMBCI3PFROQD3GAYEJCNOTSEB23PANCNFSM4QXE5EOQ
> >
> >> .
> >>
> >
>
> —
> You are receiving this because your review was requested.
> Reply to this email directly, view it on GitHub
> <https://github.com/kotest/kotest/pull/1687#issuecomment-686920849>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAFVSGTTCTPIY47CABXWN63SEB4SBANCNFSM4QXE5EOQ>
> .
>

2020-09-04 13:04 UTC, LeoColman commented
I tried that as well, but it won't work when you try to use it on a class.

Unless it supports subclasses, that `KClass<EnabledCondition>` is useless, and thus requires the generic type

2020-09-04 13:22 UTC, LeoColman commented
Hmm... I might actually be able to add it as a contravariant generic. It may work
Let me tweak it

2020-09-04 13:30 UTC, LeoColman commented
@sksamuel take a look now

2020-09-04 16:17 UTC, sksamuel requested changes
Overall looks great, just a couple of tweaks needed.

2020-09-04 16:17 UTC, sksamuel commented on kotest-framework/kotest-framework-api/src/commonMain/kotlin/io/kotest/core/annotation/specAnnotations.kt
> + * to define if a test will be instantiated or executed.
to define if a spec will be instantiated or executed

2020-09-04 16:17 UTC, sksamuel commented on kotest-framework/kotest-framework-api/src/commonMain/kotlin/io/kotest/core/annotation/specAnnotations.kt
> +abstract class SpecEnabledIf {
I think EnabledCondition is better.

2020-09-04 16:17 UTC, sksamuel commented on kotest-framework/kotest-framework-engine/src/commonMain/kotlin/io.kotest.engine/extensions/IgnoredSpecDiscoveryExtension.kt
> +         .filterNot { it.hasAnnotation<Ignored>() || !it.isEnabled() }
I think it's clearer if we add another discovery extension. Separation of concerns.

2020-09-05 00:26 UTC, LeoColman commented
@sksamuel 
Please take a look if this pleases you

2020-09-05 01:55 UTC, sksamuel approved these changes

2020-09-05 02:12 UTC, merged