Add data driven in root scope
kotest/kotest pull request #1968
Opened 2021-01-05 00:04 UTC by jschneidereit

Should fix #1967 - I only added the overload to one spec since all of the data driven specs are disabled right now

2021-01-05 00:08 UTC, jschneidereit commented on kotest-framework/kotest-framework-api/src/commonMain/kotlin/io/kotest/core/datatest/datatest.kt
> +suspend fun <T : Any> ContainerScope.forAll(vararg data: Pair<String, T>, test: suspend (T) -> Unit) = forAll(data.toList(), test)
Tomorrow morning I need to verify that this won't get confused with the `List<T>` overload

2021-01-05 16:14 UTC, sksamuel requested changes
Looks good. I would like to see the test added to the other spec types too, so that we know it works on all (where applicable).

2021-01-05 16:14 UTC, sksamuel commented on kotest-framework/kotest-framework-api/src/commonMain/kotlin/io/kotest/core/datatest/datatestconcurrent.kt
> +package io.kotest.core.datatest
I would rather these live in the same file so avoid import clashes. That way when you import forAll from this package, you can use it in both root scope and container scope in the same spec.

2021-01-06 12:18 UTC, sksamuel approved these changes

2021-01-06 12:18 UTC, merged