#2312 Makes beforeAll and afterAll suspend functions
kotest/kotest pull request #2333
Opened 2021-06-25 17:32 UTC by ashishkujoy

2021-07-03 00:21 UTC, sksamuel commented
This is a breaking change. What about deprecating the old names, and adding beforeProject / afterProject as suspend equivalents ?

2021-07-04 04:07 UTC, ashishkujoy commented
> This is a breaking change. What about deprecating the old names, and adding beforeProject / afterProject as suspend equivalents ?

Sure make sense.

2021-07-04 04:31 UTC, sksamuel requested changes
Looks good but we should still call both methods from the created config, otherwise people's listeners will silently start to fail in 5.0.

2021-07-04 23:53 UTC, sksamuel approved these changes

2021-07-06 05:27 UTC, merged