YearMonth Arbitrary implementation
kotest/kotest pull request #2935
Opened 2022-04-22 11:53 UTC by nor-ek

Tests
Edge cases:
- Minimum of the range
- Max of the range
- All leap february in the range

Closes #2928

2022-04-22 16:08 UTC, LeoColman requested changes

2022-04-22 16:08 UTC, LeoColman commented on kotest-property/src/jvmTest/kotlin/com/sksamuel/kotest/property/arbitrary/DateTest.kt
> +      }
```suggestion
      "generate valid YearMonths" {
         shouldNotThrowAny {
             Arb.yearMonth().take(10_000).toList()
         }
      }
```

2022-04-22 16:08 UTC, LeoColman commented on kotest-property/src/jvmTest/kotlin/com/sksamuel/kotest/property/arbitrary/DateTest.kt
> +         months shouldBe (1..12).toSet()
I think this test needs improvement.

We're not guaranteeing here that we're not generating YearMonths from outside the range specified

2022-04-22 16:08 UTC, LeoColman commented on kotest-property/src/jvmTest/kotlin/com/sksamuel/kotest/property/arbitrary/DateTest.kt
> +      }
This adds to my previous comment about improving the tests.
I think having some glanularity for months should be validated in the tests as well

2022-04-22 16:08 UTC, LeoColman commented on kotest-property/src/jvmTest/kotlin/com/sksamuel/kotest/property/arbitrary/DateTest.kt
> +      "Contain now if leap year" {
I'd say that maybe `now` should always be a constant if it's within the range

2022-04-22 16:08 UTC, LeoColman commented on kotest-property/src/jvmMain/kotlin/io/kotest/property/arbitrary/dates.kt
> +   val february28s = leapYears.map { YearMonth.of(it, 2) }
It's possible to simplify this logic a bit:

```
val yearMonthRange = (minYearMonth..maxYearMonth) // Maybe this method doesn't exist, but something similar might
val leapYearMonths = yearMonthRange.filter { isLeap(it.year) }

val edgeCases = leapYearMonths
// ...

```

2022-04-22 16:09 UTC, LeoColman commented
Nice pull request, @nor-ek ! 😄

2022-04-25 12:31 UTC, nor-ek commented on kotest-property/src/jvmMain/kotlin/io/kotest/property/arbitrary/dates.kt
> +   val february28s = leapYears.map { YearMonth.of(it, 2) }
It's impossible to filter ClosedRange :/  However I've simplified it a bit by removing now from leap years.

2022-04-25 12:33 UTC, no-u42 commented on kotest-property/src/jvmTest/kotlin/com/sksamuel/kotest/property/arbitrary/DateTest.kt
> +      }
I've also improved `generate valid LocalDates (no exceptions)` by this assertion.

2022-04-25 12:38 UTC, nor-ek commented
@LeoColman thanks for review. I've improved it a bit. Not sure about https://github.com/kotest/kotest/pull/2935#discussion_r856376041 how would you do this?

2022-04-30 10:35 UTC, sksamuel commented
> @LeoColman thanks for review. I've improved it a bit. Not sure about [#2935 (comment)](https://github.com/kotest/kotest/pull/2935#discussion_r856376041) how would you do this?

Maybe just a single test with a specific year range ?

2022-05-03 15:38 UTC, nor-ek commented
Okay so let's say it's done. I removed this test in case of test `generate YearMonths between minYearMonth and maxYearMonth` is checking specific yearMonthRange.

2022-05-03 17:46 UTC, merged

2022-05-03 17:46 UTC, sksamuel commented
👍🏼