shouldBe/shouldNotBe chain
kotest/kotest pull request #3186
Opened 2022-08-28 19:21 UTC by sksamuel

Closes #3170

2022-08-31 15:21 UTC, LeoColman requested changes
Missing some tests on the return

2022-09-26 22:37 UTC, LeoColman approved these changes

2022-09-28 18:03 UTC, LeoColman approved these changes

2022-11-01 21:24 UTC, myuwono approved these changes

2023-04-01 22:37 UTC, merged

2023-04-26 01:44 UTC, philBrown commented
This represents a breaking change to the API and should never have been released as a minor update