Added shouldMatchResource, shouldNotMatchResource matchers (#2945)
kotest/kotest pull request #3241
Opened 2022-10-14 15:53 UTC by bzareba

2022-10-17 16:03 UTC, LeoColman requested changes
What should happen when resources are binaries or any format other than text?
Can we add some test cases to cover this?

2022-10-17 16:03 UTC, LeoColman commented on kotest-assertions/kotest-assertions-core/src/jvmMain/kotlin/io/kotest/matchers/resource/matchers.kt
> +   contract {
fancy!

2022-10-18 14:00 UTC, bzareba commented
@LeoColman Hi, I think we should let users compare string to any file. I've added test case to cover this. 

When it comes to binary files I think something like `ByteArray shouldMatchResource "/resource.bin"` would be a better fit.

2022-10-24 08:57 UTC, Kantis commented
Can we let the user provide a matcher to compare actual with resource content with? For instance, what if the resource contains a json blob and you want to compare specific fields of the json.

Current implementation could also see issues due to line endings

2022-11-17 14:36 UTC, bzareba commented
@Kantis I've added possibility to add custom matcher in form of matcher provider, so the usage is:
`givenValue.shouldMatchResource("/testResource.txt", ::startWith)`
or like this, enabling resource value modification before compare:
~`givenValue.shouldMatchResource("/testResource.txt") { s -> startWith(s.lowercase()) }`~

edit: I've added optional `ignoreLineSeparators` parameter so the syntax with lambda is:
`givenValue.shouldMatchResource("/testResource.txt", { s -> startWith(s.lowercase()) })`

2022-11-18 07:15 UTC, bzareba commented
I also added possibility to ignore line separators differences. I made it default behavior.

2022-12-05 00:13 UTC, sksamuel commented
@bzareba looks great. I think @LeoColman wanted a test on non-text resource and then this is good to merge.

2022-12-05 17:09 UTC, bzareba commented
Hi @sksamuel I've added the test, but I think `ByteArray` matchers would be better with binary files, so I just added them :D I've pushed them here, please let me know if they should go in the separate PR

2022-12-06 07:24 UTC, bzareba commented
I see there are some failing tests. That is probably due to autocrlf handling in git. I'll find a way to handle this, I'm thinking of creating the resources programmatically for these tests.

2022-12-06 09:13 UTC, bzareba commented
> I'm thinking of creating the resources programmatically

I forgot that `.gitattributes` can be used to keep original line-ending for these files. It should work now. :)

2022-12-06 14:41 UTC, LeoColman approved these changes

2022-12-06 15:03 UTC, merged