Use the default spec for the first test in InstancePerTest
kotest/kotest pull request #3601
Opened 2023-07-29 21:40 UTC by sksamuel

Fixes #3490

2023-07-29 22:01 UTC, LeoColman requested changes

2023-07-29 22:01 UTC, LeoColman commented on kotest-framework/kotest-framework-engine/src/jvmMain/kotlin/io/kotest/engine/spec/tempfile.kt
> +   println("Creating file!!")
oopsie

2023-07-29 22:01 UTC, LeoColman requested changes

2023-07-29 22:01 UTC, LeoColman commented on kotest-framework/kotest-framework-engine/src/jvmMain/kotlin/io/kotest/engine/spec/tempfile.kt
> +   println("Creating file!!")
```suggestion
  
```

2023-08-01 20:36 UTC, Kantis commented on kotest-framework/kotest-framework-engine/src/jvmMain/kotlin/io/kotest/engine/spec/runners/InstancePerTestSpecRunner.kt
> +         createInstance(test.spec::class).flatMap { executeInGivenSpec(test, it) }
```suggestion
         executeInCleanSpec(test)
```

Duplicating the code of `executeInCleanSpec` here, I think?

2023-08-27 02:11 UTC, merged