Updated to kotlin 2.0
kotest/kotest pull request #4248
Opened 2024-08-03 07:26 UTC by sksamuel

I've set it to 2.0.20 RC because by the time we release 6.0, Kotlin 2.0.20 will certainly be out

2024-08-03 07:39 UTC, sksamuel commented
@aSemy do we define the kotlin SDK version anywhere?
Like in some other projects I do
```
   tasks.withType<org.jetbrains.kotlin.gradle.tasks.KotlinCompile> {
      kotlinOptions.apiVersion = "1.9"
      kotlinOptions.languageVersion = "1.9"
   }
```

2024-08-03 08:27 UTC, aSemy commented
I think no, the api/language levels aren't set, so they'll default to 1.9. 

I suggest we set the api/language level to 2.0. Since Kotest 6.0 is a major release we can focus on supporting newer versions.

2024-08-03 18:21 UTC, sksamuel commented
> I think no, the api/language levels aren't set, so they'll default to 1.9.
> 
> I suggest we set the api/language level to 2.0. Since Kotest 6.0 is a major release we can focus on supporting newer versions.

ok done

2024-08-03 21:25 UTC, sksamuel commented
@aSemy this is good for review

2024-08-05 13:57 UTC, OliverO2 requested changes

2024-08-05 13:57 UTC, OliverO2 commented on kotest-framework/kotest-framework-engine/src/commonMain/kotlin/io/kotest/engine/test/TestCaseExecutor.kt
> +               if (platform == Platform.JVM && testCase.config.testCoroutineDispatcher) createTestDispatcherInterceptor() else null,
This is made obsolete by #4251, right? So the entire expect/actual `createTestDispatcherInterceptor()` could either be deleted or used with...

2024-08-05 13:57 UTC, OliverO2 commented on kotest-framework/kotest-framework-engine/src/commonMain/kotlin/io/kotest/engine/test/TestCaseExecutor.kt
>                 if (useCoroutineTestScope) TestCoroutineInterceptor() else null,
... this one. But in that case, we'd need to remove `useCoroutineTestScope`.

Of course, we could throw an exception if a `coroutineTestScope` was requested but the platform does not support it. But I wonder if it would be easier to have the entire logic here in one place instead of distributing it across an expect/actual hierarchy. It seems to be a temporary state waiting for a fix, after all.

2024-08-05 13:57 UTC, OliverO2 commented on kotest-assertions/kotest-assertions-core/src/commonMain/kotlin/io/kotest/matchers/collections/CollectionMatchers.kt
> +      { "${actual.print().value} should not match the predicates in order" }
How is this related to Kotlin 2.0?

2024-08-05 14:04 UTC, sksamuel commented on kotest-framework/kotest-framework-engine/src/commonMain/kotlin/io/kotest/engine/test/TestCaseExecutor.kt
>                 if (useCoroutineTestScope) TestCoroutineInterceptor() else null,
Yes it'll be removed in that other PR.

2024-08-05 14:04 UTC, sksamuel commented on kotest-assertions/kotest-assertions-core/src/commonMain/kotlin/io/kotest/matchers/collections/CollectionMatchers.kt
> +      { "${actual.print().value} should not match the predicates in order" }
The toString on lambas changed in 2.0

2024-08-05 14:04 UTC, sksamuel commented on kotest-framework/kotest-framework-engine/src/commonMain/kotlin/io/kotest/engine/test/TestCaseExecutor.kt
> +               if (platform == Platform.JVM && testCase.config.testCoroutineDispatcher) createTestDispatcherInterceptor() else null,
Yes, it's in the other PR.

2024-08-05 14:16 UTC, OliverO2 commented on kotest-framework/kotest-framework-engine/src/commonMain/kotlin/io/kotest/engine/test/TestCaseExecutor.kt
>                 if (useCoroutineTestScope) TestCoroutineInterceptor() else null,
Don't the two PRs now contradict each other? Doesn't the code added here collide with the removal of #4251?

2024-08-05 14:31 UTC, sksamuel commented on kotest-framework/kotest-framework-engine/src/commonMain/kotlin/io/kotest/engine/test/TestCaseExecutor.kt
>                 if (useCoroutineTestScope) TestCoroutineInterceptor() else null,
I did this first to make it compile. Kotlin 2 didn't like the class not being abstract. This was to get it to compile. The other one I'll rebase after. It's only because I did this first

2024-08-05 14:34 UTC, OliverO2 approved these changes

2024-08-05 16:07 UTC, merged

2024-08-06 13:06 UTC, JesusMcCloud commented
Not trying to be a petty necromancer and resurrect closed issues, but how does this affect #4177?