feat: add Yaml matchers module
kotest/kotest pull request #4443
Opened 2024-10-18 12:42 UTC by rbraeunlich

Hi everyone,
I started working on the Yaml matchers feature. In order to have a starting point for discussions/suggestions/improvements I open this PR quite early in draft mode. I had to set the Java version to 11 for now since I'm still working on upgrading KAML to Java 8 compatibility.
The 
```
   id("kotest-jvm-conventions")
   id("kotest-js-conventions")
```
can also be replaced later with the multiplatform-conversions, but this also requires a newer KAML version.
If you have ideas for additional matchers or a different file structure feel free to point it out, I'll happily adjust the code.

2024-10-30 14:59 UTC, AlexCue987 commented
can you run `apiDump`?

2024-10-31 05:05 UTC, rbraeunlich commented
Sorry, forgot that one 😅 I added the API file.

2024-10-31 12:27 UTC, AlexCue987 requested changes
LGTM, let's just expose the new docs page via navigation

2024-10-31 12:27 UTC, AlexCue987 commented on documentation/docs/assertions/yaml.md
> +---
can you add a link to this doc from `documentation/sidebars.js`?

2024-10-31 14:00 UTC, rbraeunlich commented on documentation/docs/assertions/yaml.md
> +---
Done!

2024-10-31 15:16 UTC, AlexCue987 approved these changes
very nice!

2024-10-31 16:07 UTC, merged