Add Javadocs to methods in unique.kt
kotest/kotest pull request #4614
Opened 2024-12-31 19:25 UTC by LeoColman

Also did some code-golfing to reduce functions to one-liners

2024-12-31 20:41 UTC, AlexCue987 requested changes
Overall LGTM, but two examples look wrong to me

2024-12-31 20:41 UTC, AlexCue987 commented on kotest-assertions/kotest-assertions-core/src/commonMain/kotlin/io/kotest/matchers/collections/unique.kt
> + * array.shouldBeUnique(String.CASE_INSENSITIVE_ORDER)   // Assertion passes
should it be `CASE_SENSITIVE_ORDER`? because it's not unique when `"APPLE" == "apple"`

2024-12-31 20:41 UTC, AlexCue987 commented on kotest-assertions/kotest-assertions-core/src/commonMain/kotlin/io/kotest/matchers/collections/unique.kt
> + * list.shouldBeUnique(String.CASE_INSENSITIVE_ORDER)   // Assertion passes
same suggestion here: let's make it case sensitive

2024-12-31 23:32 UTC, AlexCue987 approved these changes

2025-01-01 03:33 UTC, LeoColman commented
@AlexCue987 both examples fixed and also added tests to validate them.

There is no "ConsiderCase", so I had to improvise

2025-01-01 03:46 UTC, merged