Provide range-based numeric generators #530
kotest/kotest pull request #543
Opened 2019-01-13 20:01 UTC by sksamuel

2019-01-13 22:47 UTC, LeoColman approved these changes

2019-01-13 22:47 UTC, Kerooker commented on kotlintest-assertions/src/main/kotlin/io/kotlintest/properties/Gen.kt
> +      override fun constants(): Iterable<LocalDate> = emptyList()
Interesting dates to be constants: February 28th, February 29th, Jan 1st and Dec 31st

2019-01-13 22:47 UTC, Kerooker commented on kotlintest-assertions/src/main/kotlin/io/kotlintest/properties/Gen.kt
> +      override fun random(): Sequence<LocalDate> = generateSequence { LocalDate.of(RANDOM.nextInt(maxYear - minYear) + minYear, RANDOM.nextInt(12) + 1, RANDOM.nextInt(31) + 1) }
Bad randoms. Will generate February 30th, April 31st

2019-01-13 22:47 UTC, Kerooker commented on kotlintest-assertions/src/main/kotlin/io/kotlintest/properties/Gen.kt
> +    fun localDate(minYear: Int = 1, maxYear: Int = 2030): Gen<LocalDate> = object : Gen<LocalDate> {
I think that minYear should default to 1970, but I liked to be able to customize!

2019-01-13 22:47 UTC, Kerooker commented on kotlintest-assertions/src/main/kotlin/io/kotlintest/properties/Gen.kt
> +      override fun constants(): Iterable<LocalTime> = emptyList()
Maybe 00:00 and 23:59 could be good constants here?

2019-01-13 22:47 UTC, Kerooker commented on kotlintest-assertions/src/main/kotlin/io/kotlintest/properties/Gen.kt
> +      override fun random(): Sequence<LocalDateTime> = generateSequence { LocalDateTime.of(RANDOM.nextInt(maxYear - minYear) + minYear, RANDOM.nextInt(12) + 1, RANDOM.nextInt(31) + 1, RANDOM.nextInt(
Maybe better to use the other generators here. `generatedLocalDate.atTime(generatedTime)`

2019-01-13 22:47 UTC, Kerooker commented on kotlintest-assertions/src/main/kotlin/io/kotlintest/properties/Gen.kt
> +      override fun random(): Sequence<LocalDateTime> = generateSequence { LocalDateTime.of(RANDOM.nextInt(maxYear - minYear) + minYear, RANDOM.nextInt(12) + 1, RANDOM.nextInt(31) + 1, RANDOM.nextInt(
Prevents extra maintance points (although unlikely)

2019-01-13 22:47 UTC, Kerooker commented on kotlintest-assertions/src/main/kotlin/io/kotlintest/properties/Gen.kt
> +      private fun randomDuration(): Duration = when (RANDOM.nextInt(5)) {
We can reduce this code a bit, and include more constants:

```kotlin
val wantedUnits = ChronoUnit.values().filter { it <= ChronoUnit.WEEKS } // Will get all crono units that represent a week or less

return Duration.of(Random.nextLong(), wantedUnits.random())
```

2019-01-13 22:47 UTC, Kerooker commented on kotlintest-assertions/src/main/kotlin/io/kotlintest/properties/Gen.kt
> +     * Returns a [[Gen]] which is the same as [[Gen.double]]] but does not include infinity or NaN.
Does not include -INFINITY, +INFINITY or NaN

2019-01-13 22:47 UTC, Kerooker commented on kotlintest-assertions/src/main/kotlin/io/kotlintest/properties/Gen.kt
> +    fun numericDoubles(): Gen<Double> = object : Gen<Double> {
For this to be range-based, we should add a `minValue` and `maxValue`

2019-01-13 22:47 UTC, Kerooker commented on kotlintest-assertions/src/main/kotlin/io/kotlintest/properties/Gen.kt
> +     * Returns a [[Gen]] which is the same as [[Gen.float]]] but does not include infinity or NaN.
Same comments from Double Gen

2019-01-13 22:49 UTC, LeoColman requested changes
Some changes should be made

2019-01-13 22:49 UTC, Kerooker commented
Also missing tests for the new gens and functions.

2019-01-13 22:51 UTC, sksamuel commented
Good feedback.

On Sun, 13 Jan 2019, 22:49 Leonardo Colman Lopes <notifications@github.com
wrote:

> Also missing tests for the new gens and functions.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/kotlintest/kotlintest/pull/543#issuecomment-453873056>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AAtZGokqPr4Dzk09Jsi9zUkdIlOXS49qks5vC7gOgaJpZM4Z9WML>
> .
>

2019-01-14 00:35 UTC, Kerooker commented on kotlintest-assertions/src/main/kotlin/io/kotlintest/properties/Gen.kt
> +      private fun randomDuration(): Duration = when (RANDOM.nextInt(5)) {
Would be also cool to have a Gen<> for Period

2019-01-28 21:41 UTC, Kerooker commented
@sksamuel 
I tweaked some of the generators. Could you take a look, please?

2019-01-30 20:24 UTC, sksamuel commented
Looks excellent. Feel free to merge.

2019-01-31 14:12 UTC, merged